# Site settings
title: VRHook
tag_text: VRHook
description: VRHook is a tool to collect machine learning data from off-the-shelf VR games.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["README.md"]
sass:
  style: compressed
